import { Page } from "@/components/site-chrome";
const sections = [
["§ 1 Geltungsbereich und Vertragsschluss", [
"Diese Allgemeinen Geschäftsbedingungen gelten für Druck-, Gestaltungs-, Mailing- und Webleistungen der NOXIQ GmbH, Meschwitzstraße 1, 01099 Dresden, handelnd unter OTTO-Druck (Auftragnehmer). Sie gelten gegenüber Unternehmern und Verbrauchern; ausschließlich für Unternehmer oder Kaufleute bestimmte Regelungen sind entsprechend gekennzeichnet.",
"Die Darstellung auf dieser Website und das Absenden einer Projektanfrage sind noch kein verbindliches Angebot und keine Bestellung. Nach Klärung der Anforderungen erhält der Auftraggeber ein Angebot. Ein Vertrag kommt durch dessen unveränderte Annahme innerhalb der angegebenen Bindungsfrist zustande. Ist das Angebot ausdrücklich freibleibend, kommt der Vertrag erst durch unsere Auftragsbestätigung in Textform, etwa per E-Mail, zustande.",
"Individuelle Vereinbarungen haben Vorrang. Abweichende Geschäftsbedingungen des Auftraggebers gelten nur, wenn wir ihrer Geltung zugestimmt haben. Gesetzliche Formvorschriften bleiben unberührt."
]],
["§ 2 Preise und nachträgliche Änderungen", [
"Maßgeblich sind die im Angebot vereinbarten Leistungen, Mengen, Preise und die dort genannte Bindungsfrist. Bei Lieferung an Dritte bleibt der Besteller Auftraggeber, sofern nichts anderes vereinbart wurde. Gegenüber Verbrauchern werden Gesamtpreise einschließlich Umsatzsteuer angegeben; gegenüber Unternehmern können ausdrücklich bezeichnete Nettopreise zuzüglich Umsatzsteuer vereinbart werden. Verpackung, Versand, Porto und sonstige Zusatzkosten werden vor Vertragsschluss ausgewiesen.",
"Ändern sich die Auftragsdaten vor Vertragsschluss, erstellen wir bei Bedarf ein angepasstes Angebot. Nach Vertragsschluss werden zusätzliche Leistungen oder Änderungen, einschließlich zusätzlicher Korrekturen und Probeandrucke, nur nach vorheriger Abstimmung der Mehrkosten und Zustimmung des Auftraggebers berechnet. Bereits vereinbarte Preise ändern sich nicht einseitig."
]],
["§ 3 Vorkasse, Zahlungsarten und Produktionsbeginn", [
"Druckaufträge werden gegen vollständige Vorkasse ausgeführt. Nach Vertragsschluss erhält der Auftraggeber eine Vorausrechnung. Der gesamte Rechnungsbetrag ist ohne Abzug innerhalb der auf der Rechnung angegebenen Zahlungsfrist zu zahlen; fehlt eine Frist, ist er nach Zugang der Rechnung fällig. Individuell vereinbarte Zahlungsbedingungen und gesetzliche Leistungsverweigerungsrechte bleiben unberührt.",
"Die Zahlung erfolgt per Banküberweisung auf das in der Rechnung genannte Konto der NOXIQ GmbH. Eine SEPA-Echtzeitüberweisung kann genutzt werden, soweit die beteiligten Zahlungsdienstleister diese unterstützen. Bitte geben Sie die Rechnungsnummer als Verwendungszweck an. Maßgeblich ist der tatsächliche Zahlungseingang; ein Überweisungsbeleg allein ersetzt ihn nicht. Andere Zahlungsarten stehen nur zur Verfügung, wenn sie im jeweiligen Angebot ausdrücklich vereinbart wurden.",
"Sobald der vollständige Rechnungsbetrag eingegangen ist und sämtliche druckfähigen Daten sowie die erforderliche Druckfreigabe vorliegen, wird die Produktion unverzüglich im Rahmen der vereinbarten Produktionszeiten veranlasst. Zahlungseingang allein ersetzt keine Druckfreigabe. Vereinbarte Lieferfristen berücksichtigen diese Voraussetzungen; Verzögerungen durch fehlende Zahlungen, Daten oder Freigaben werden dem Auftraggeber mitgeteilt. Ein sofortiger Versand ist damit nicht zugesagt.",
"Für gesondert beauftragte Gestaltungs- und Webleistungen werden Zahlungsplan und Leistungsbeginn im Angebot festgelegt. Bestehende Verträge werden durch diese Bedingungen nicht nachträglich geändert.",
"Eine Aufrechnung ist mit unbestrittenen oder rechtskräftig festgestellten Forderungen sowie mit Gegenforderungen aus demselben Vertragsverhältnis möglich. Gesetzliche Zurückbehaltungsrechte bleiben bestehen. Bei Zahlungsverzug gelten die gesetzlichen Verzugszinsen und Voraussetzungen für weiteren Verzugsschaden. Eine Gefährdung des Zahlungsanspruchs berechtigt uns nur im gesetzlich vorgesehenen Umfang zur Leistungsverweigerung oder zum Verlangen einer Sicherheit."
]],
["§ 4 Lieferung, Versand und Kooperationspartner", [
"Liefertermine sind verbindlich, wenn sie ausdrücklich als solche vereinbart wurden. Zumutbare Teillieferungen bedürfen der Abstimmung; zusätzliche Versandkosten entstehen dem Auftraggeber hierdurch nur nach seiner Zustimmung. Bei Lieferverzug bestehen die gesetzlichen Rechte, einschließlich eines Rücktritts nach erforderlicher Fristsetzung oder ohne Fristsetzung, soweit das Gesetz dies vorsieht.",
"Wir können geeignete Kooperationspartner mit Produktion und Versand beauftragen. Bei einem Vertrag mit der NOXIQ GmbH bleiben wir Vertragspartner und für unsere vertraglichen Pflichten verantwortlich. Eine unmittelbare Beauftragung oder Rechnungsstellung eines anderen Unternehmens erfolgt nur auf Grundlage einer gesonderten, vorab offengelegten Vereinbarung. Dessen AGB werden nicht automatisch Bestandteil unseres Vertrags.",
"Beim Versand an Verbraucher richtet sich der Gefahrübergang nach den gesetzlichen Verbraucherschutzvorschriften. Bei Unternehmern geht die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung beim Versendungskauf nach Maßgabe des § 447 BGB mit Übergabe an das Transportunternehmen über. Unsere Haftung für eigenes Verschulden bleibt unberührt.",
"Bei nicht von uns zu vertretenden, unvorhersehbaren Ereignissen höherer Gewalt informieren wir unverzüglich über die Auswirkungen und die voraussichtliche Dauer. Gesetzliche Rücktritts-, Kündigungs- und Erstattungsrechte bleiben erhalten. Für Verpackungen erfüllen wir die jeweils anwendbaren gesetzlichen Rücknahme- und Verwertungspflichten; Einzelheiten einer erforderlichen Rückgabe werden mitgeteilt.",
"An überlassenen Gegenständen können gesetzliche Zurückbehaltungsrechte bestehen; § 369 HGB gilt nur bei Vorliegen seiner kaufmännischen Voraussetzungen."
]],
["§ 5 Eigentumsvorbehalt", [
"Gelieferte Ware bleibt bis zur vollständigen Bezahlung der zugehörigen Forderung unser Eigentum. Gegenüber Unternehmern erstreckt sich der Eigentumsvorbehalt auf sämtliche Forderungen aus der laufenden Geschäftsverbindung.",
"Unternehmer dürfen Vorbehaltsware im ordnungsgemäßen Geschäftsgang weiterveräußern. Die daraus entstehenden Forderungen werden bereits jetzt bis zur Höhe unserer offenen Forderungen an uns abgetreten; wir nehmen die Abtretung an. Die Einziehung bleibt bis zu einem berechtigten Widerruf, insbesondere bei Zahlungsverzug, zulässig. Dann sind die zur Einziehung erforderlichen Angaben zu machen.",
"Bei Verarbeitung oder Verbindung von Vorbehaltsware durch Unternehmer erwerben wir, soweit rechtlich möglich, Miteigentum im Verhältnis des Rechnungswerts unserer Ware zum Wert des neuen Erzeugnisses. Übersteigt der realisierbare Sicherungswert die gesicherten Forderungen um mehr als zehn Prozent, geben wir auf Verlangen entsprechende Sicherheiten nach unserer Wahl frei."
]],
["§ 6 Druckdaten, Freigabe, Abweichungen und Mängel", [
"Der Auftraggeber stellt vereinbarte Daten, Vorlagen, Materialien und Angaben rechtzeitig bereit. Inhaltliche, sprachliche oder rechtliche Prüfungen sowie umfassende Datenkorrekturen sind nur geschuldet, wenn sie beauftragt wurden. Vereinbarte technische Datenprüfungen und unsere gesetzlichen Hinweis- und Sorgfaltspflichten bleiben unberührt.",
"Korrekturabzüge und Freigabevorlagen sind sorgfältig auf Inhalt, Schreibweise, Maße und Gestaltung zu prüfen. Für darin erkennbare und ausdrücklich freigegebene Fehler ist der Auftraggeber verantwortlich, soweit uns keine eigene Pflichtverletzung trifft. Produktionsfehler nach der Freigabe bleiben in unserer Verantwortung.",
"Farbdarstellungen auf Bildschirmen sind ohne vereinbarte verbindliche Farbvorlage nicht farbverbindlich. Technisch bedingte geringfügige Abweichungen sind nur insoweit zulässig, wie sie die vereinbarte Beschaffenheit und den Vertragszweck nicht beeinträchtigen und dem Auftraggeber zumutbar sind. Verbindlich vereinbarte Farben, Materialien und Qualitätsmerkmale bleiben maßgeblich.",
"Mehr- oder Minderlieferungen und ihre Abrechnung werden gegebenenfalls produktspezifisch vor Vertragsschluss vereinbart. Eine pauschale Mengentoleranz von zehn Prozent gilt nicht. Materialmängel werden nicht allein durch Abtretung von Ansprüchen gegen Zulieferer auf den Auftraggeber verlagert.",
"Es gelten die gesetzlichen Mängelrechte und Verjährungsfristen. Eine allgemeine Ausschlussfrist von einer Woche besteht nicht. Ist der Kauf für beide Seiten ein Handelsgeschäft, gelten die Untersuchungs- und Rügepflichten des § 377 HGB. Verbraucher verlieren ihre Mängelrechte nicht allein dadurch, dass sie einen Mangel nicht sofort anzeigen.",
"Nacherfüllung, Rücktritt, Minderung und Schadensersatz richten sich nach den gesetzlichen Voraussetzungen; eine pauschale Begrenzung der Nacherfüllung auf den Auftragswert erfolgt nicht. Bei Mängeln einer Teillieferung bestimmen sich die Rechte hinsichtlich der übrigen Lieferung ebenfalls nach dem Gesetz."
]],
["§ 7 Haftung", [
"Wir haften unbeschränkt für vorsätzlich oder grob fahrlässig verursachte Schäden und für schuldhafte Verletzungen von Leben, Körper oder Gesundheit. Gleiches gilt im Rahmen übernommener Garantien sowie bei zwingender gesetzlicher Haftung, insbesondere nach dem Produkthaftungsgesetz.",
"Bei leicht fahrlässiger Verletzung einer wesentlichen Vertragspflicht ist die Haftung auf den vertragstypischen, bei Vertragsschluss vorhersehbaren Schaden begrenzt. Wesentlich sind Pflichten, deren Erfüllung die ordnungsgemäße Vertragsdurchführung erst ermöglicht und auf deren Einhaltung der Auftraggeber regelmäßig vertrauen darf. Im Übrigen ist die Haftung für leichte Fahrlässigkeit ausgeschlossen. Diese Regelungen gelten auch zugunsten unserer gesetzlichen Vertreter und Erfüllungsgehilfen."
]],
["§ 8 Wiederkehrende Arbeiten", [
"Für regelmäßig wiederkehrende Leistungen werden Laufzeit, Leistungsumfang und Kündigung im jeweiligen Angebot festgelegt. Bei unbefristeten Verträgen mit Unternehmern gilt mangels anderer Vereinbarung eine Kündigungsfrist von drei Monaten zum Monatsende. Gegenüber Verbrauchern gelten die gesetzlichen Vorgaben und die ausdrücklich vereinbarten zulässigen Laufzeiten und Kündigungsfristen. Das Recht zur außerordentlichen Kündigung aus wichtigem Grund bleibt unberührt."
]],
["§ 9 Rechte an bereitgestellten Inhalten", [
"Der Auftraggeber stellt sicher, dass er die für die vereinbarte Nutzung erforderlichen Rechte an überlassenen Texten, Bildern, Logos, Schriften und sonstigen Inhalten besitzt. Er informiert uns über ihm bekannte Nutzungsbeschränkungen.",
"Verletzt der Auftraggeber diese Pflicht schuldhaft, stellt er uns von berechtigten Ansprüchen Dritter und erforderlichen, angemessenen Rechtsverteidigungskosten frei, soweit er für die Rechtsverletzung verantwortlich ist. Wir informieren ihn unverzüglich und stimmen die Verteidigung mit ihm ab. Eigene Verantwortungsanteile von uns bleiben berücksichtigt."
]],
["§ 10 Entwürfe, Gestaltungen und Nutzungsrechte", [
"Bei beauftragten Entwürfen, Layouts, Datensätzen, Templates, Programmierungen und anderen Gestaltungen bestimmen Angebot und Leistungsbeschreibung die geschuldeten Ergebnisse und Nutzungsrechte. Urheberrechtlicher Schutz besteht nach den gesetzlichen Voraussetzungen; er wird nicht unabhängig von der erforderlichen Schutzfähigkeit unterstellt.",
"Mit vollständiger Zahlung erhält der Auftraggeber die vereinbarten Nutzungsrechte. Fehlt eine ausdrückliche Festlegung, werden die für den vertraglich vorausgesetzten Zweck erforderlichen Nutzungsrechte eingeräumt. Erweiterte Nutzungen können eine zusätzliche Vereinbarung und Vergütung erfordern. Rechte Dritter, insbesondere an Schriften, Fotos, Software und anderen Lizenzbestandteilen, bleiben ihren jeweiligen Lizenzbedingungen unterworfen.",
"Bearbeitungen und Weitergabe richten sich nach den eingeräumten Rechten und dem Gesetz. Ein pauschales Verbot jeder Änderung oder Nachahmung gilt nicht. Gesetzlich entstehende Miturheberrechte des Auftraggebers werden nicht ausgeschlossen. Eine vereinbarte Vergütung für Präsentationen vergütet diese Leistung; zusätzliche Verwertungsrechte entstehen nur nach Vereinbarung.",
"Offene Arbeitsdateien, Quellcodes und interne Produktionsmittel werden nur herausgegeben, soweit dies zum vereinbarten Leistungsumfang gehört oder gesetzlich geschuldet ist. Vereinbarte Enddateien und vom Auftraggeber bereitgestellte Originale werden hiervon nicht erfasst. Eine dauerhafte Archivierung ist ohne gesonderte Vereinbarung nicht geschuldet."
]],
["§ 11 Herstellerhinweise und Referenzen", [
"Hinweise auf unsere Firma, Signaturen auf Erzeugnissen und die Verwendung von Kundenarbeiten, Namen oder Logos für unsere Eigenwerbung erfolgen nur mit vorheriger Zustimmung des Auftraggebers beziehungsweise auf einer sonstigen nachweisbaren Rechtsgrundlage. Vertraulichkeitsabreden und Rechte Dritter bleiben unberührt."
]],
["§ 12 Erfüllungsort, Gerichtsstand und Schlussbestimmungen", [
"Es gilt deutsches Recht unter Ausschluss des UN-Kaufrechts. Bei Verbrauchern bleiben zwingende Schutzvorschriften des Staates ihres gewöhnlichen Aufenthalts unberührt, soweit sie anwendbar sind.",
"Für Kaufleute, juristische Personen des öffentlichen Rechts und öffentlich-rechtliche Sondervermögen wird Dresden als Gerichtsstand vereinbart. Im Übrigen gelten die gesetzlichen Zuständigkeitsregeln. Der Erfüllungsort richtet sich nach der jeweiligen Vereinbarung und den gesetzlichen Vorschriften.",
"Sollte eine Bestimmung unwirksam sein, gelten die gesetzlichen Rechtsfolgen. Die Wirksamkeit der übrigen Bestimmungen bleibt nach Maßgabe des Gesetzes unberührt."
]],
["§ 13 Personalisierte Mailings und Datenschutz", [
"Empfängerdaten dürfen nur übermittelt und verarbeitet werden, soweit dies rechtmäßig ist. Zweck, Datenumfang, Übertragung, Aufbewahrung und Löschung werden vor der Verarbeitung abgestimmt. Ist eine Auftragsverarbeitung gegeben, wird vor Beginn eine Vereinbarung nach Artikel 28 DSGVO geschlossen, einschließlich der erforderlichen Regelungen für Unterauftragnehmer.",
"Adresslisten und andere personenbezogene Mailingdaten sind nicht für das allgemeine Anfrageformular oder den allgemeinen Druckdaten-Upload bestimmt. Hierfür vereinbaren wir einen geeigneten geschützten Übertragungsweg. Weitere Informationen zur Verarbeitung von Kontakt- und Anfragedaten enthält unsere Datenschutzerklärung."
]],
["§ 14 Webleistungen", [
"Bei Webprojekten regelt das Angebot insbesondere Seitenumfang, Funktionen, technische Umgebung, Mitwirkung, Übergabe und gegebenenfalls Abnahme. Hosting, Domainkosten, Drittanbieter-Lizenzen, Wartung und laufende Pflege sind nur enthalten, wenn sie ausdrücklich vereinbart wurden. Gesetzliche Pflichten, insbesondere anwendbare Aktualisierungspflichten, bleiben unberührt.",
"Der Auftraggeber liefert vereinbarte Inhalte und Zugangsdaten rechtzeitig. Zusatzwünsche und Änderungen werden hinsichtlich Aufwand, Vergütung und Terminen abgestimmt. Eine bestimmte Suchmaschinenplatzierung oder ein bestimmter wirtschaftlicher Erfolg wird ohne ausdrückliche Vereinbarung nicht zugesagt."
]],
["§ 15 Verbraucher und Widerruf", [
"Bei Fernabsatzverträgen oder außerhalb von Geschäftsräumen geschlossenen Verträgen können Verbrauchern gesetzliche Widerrufsrechte zustehen. Soweit erforderlich, erhalten sie vor Vertragsschluss eine gesonderte Widerrufsbelehrung und das Muster-Widerrufsformular.",
"Bei nicht vorgefertigten Waren, deren Herstellung durch eine individuelle Auswahl oder Bestimmung des Verbrauchers geprägt ist, oder bei eindeutig auf persönliche Bedürfnisse zugeschnittenen Waren kann das Widerrufsrecht nach § 312g Absatz 2 Nummer 1 BGB ausgeschlossen sein. Dies ist kein pauschaler Ausschluss für sämtliche Druck- oder Gestaltungsleistungen.",
"Bei Dienstleistungen innerhalb der Widerrufsfrist werden die erforderlichen ausdrücklichen Erklärungen zum vorzeitigen Leistungsbeginn gesondert eingeholt. Eine Zahlung oder Druckfreigabe allein ersetzt diese nicht. Gesetzliche Mängelrechte bleiben auch bei individuell angefertigten Waren bestehen."
]]
] as const;
export default function Terms(){return <Page eyebrow="Rechtliches" title="Allgemeine Geschäftsbedingungen" intro="NOXIQ GmbH · OTTO-Druck – Bedingungen für Druck, Gestaltung, Mailings und Webleistungen."><section className="legal content-section"><p>Stand: 16. September 2026</p>{sections.map(([title,paragraphs])=><section key={title} id={title.startsWith("§ 3 ")?"zahlung":undefined}><h2>{title}</h2>{paragraphs.map((text,i)=><p key={i}>{i+1}. {text}</p>)}</section>)}</section></Page>}
