import {Page} from "@/components/site-chrome";
import RevealGrid from "@/components/reveal-grid";
import {ArrowRight} from "lucide-react";
export const metadata={title:"Design & Medien – Logo, Grafik und Layout"};
const services=[
["01","Logo & Markenauftritt","Vom ersten Zeichen bis zum stimmigen Gesamtbild: Wir entwickeln oder modernisieren Ihr Logo und stimmen Farben und Schriften aufeinander ab.","Logoentwicklung · Redesign · Corporate Design · Gestaltungsrichtlinien"],
["02","Geschäftsausstattung","Ein einheitlicher Auftritt im täglichen Kontakt – sorgfältig gestaltet und für den jeweiligen Einsatz vorbereitet.","Visitenkarten · Briefpapier · Umschläge · Mappen · Vorlagen","/assets/design-service-02.webp"],
["03","Werbung & Editorial","Wir bringen umfangreiche Informationen in eine klare Form und geben Ihrer Werbung einen erkennbaren Charakter.","Flyer · Anzeigen · Broschüren · Kataloge · Plakate · Buchcover","/assets/design-service-03.webp"],
["04","Gastronomie & Veranstaltungen","Gestaltung, die zu Ihrem Haus und Anlass passt: von der übersichtlichen Speisekarte bis zum abgestimmten Auftritt einer Veranstaltung.","Speisekarten · Getränkekarten · Gutscheine · Einladungen · Veranstaltungsprogramme","/assets/design-service-04.webp"],
["05","Verpackung & Produkt","Wir verbinden Ihre Marke mit dem Produkt und berücksichtigen dabei Format, Material und die benötigten Produktionsvorlagen.","Verpackungslayout · Etiketten · Banderolen · Tragetaschen · Werbeartikel","/assets/design-service-05.webp"],
["06","Digitale Medien","Damit Ihr Unternehmen auch auf dem Bildschirm wiedererkannt wird, übertragen wir den Markenauftritt auf Ihre digitalen Kontaktpunkte.","Social-Media-Grafiken · Werbebanner · Newsletter-Layouts · Präsentationsvorlagen","/assets/design-service-06.webp"],
["07","Beschriftung & große Formate","Eine Botschaft muss auch auf Abstand funktionieren. Wir gestalten für Flächen, Räume und mobile Werbeträger.","Fahrzeugbeschriftung · Schaufenster · Schilder · Banner · Roll-ups"],
["08","Bild, Satz & Reinzeichnung","Vorhandene Inhalte erhalten den letzten Schliff. Wir bereiten Layouts auf und stimmen die fertigen Dateien auf die spätere Verwendung ab.","Bildbearbeitung · Freisteller · Satz · Infografiken · Datenaufbereitung"]
];
const steps=[["Briefing & Angebot","Was möchten Sie erreichen, wen möchten Sie ansprechen und was ist schon vorhanden? Gemeinsam klären wir Stil, Umfang, Ausgabeformate und die nächsten Schritte."],["Konzept & Entwurf","Aus Ihren Angaben entsteht eine gestalterische Richtung. Wir zeigen Ihnen, wie Inhalte, Schrift, Farbe und Bilder zusammenwirken."],["Abstimmung & Feinschliff","Sie geben Rückmeldung; wir bearbeiten die vereinbarten Korrekturen. Anzahl der Entwürfe und Korrekturrunden legen wir im Angebot fest."],["Freigabe & Übergabe","Nach Ihrer Freigabe erhalten Sie die vereinbarten Enddateien. Auf Wunsch übernehmen wir auch die passende Druckproduktion. Nutzungsrechte und offene Dateien werden vorab abgestimmt."]];
export default function Design(){return <Page eyebrow="Design & Medien" title="Gute Gestaltung macht Ihre Marke sichtbar." intro="Ein neues Logo, eine Broschüre oder ein kompletter Markenauftritt: Wir begleiten Ihre Gestaltung persönlich – von der ersten Idee bis zur fertigen Datei und zum passenden Druckprodukt." image="/assets/design-hero.webp">
<section className="content-section split"><div className="editorial-frame"><img className="editorial-image" src="/assets/design.webp" alt="Gestaltungsarbeitsplatz mit Layout-Monitor, Grafiktablett und Entwürfen" width="1100" height="750"/></div><div><p className="eyebrow line">Ein Auftritt. Viele Möglichkeiten.</p><h2>Ihre Idee bekommt eine klare Form.</h2><p>Sie bringen Ihr Vorhaben mit. Wir entwickeln daraus einen Auftritt, der zu Ihrem Unternehmen passt und über unterschiedliche Medien hinweg wiedererkennbar bleibt.</p><p>Ob wir neu beginnen oder eine bestehende Gestaltung weiterführen: Sie haben einen festen Ansprechpartner für die Abstimmung von Gestaltung, Daten und Produktion.</p><a href="/anfrage?produkt=Grafik%20%26%20Gestaltung" className="button magenta">Gestaltung anfragen <ArrowRight size={18}/></a></div></section>
<section className="content-section design-services" id="leistungen"><div className="section-heading"><div><p className="eyebrow line">Unser Gestaltungsspektrum</p><h2>Von der Visitenkarte<br/>bis zum Markenauftritt.</h2></div><p>Einzelne Maßnahmen oder ein zusammenhängendes Gestaltungskonzept – wir stimmen die Leistungen auf Ihr Vorhaben ab.</p></div><RevealGrid className="design-service-grid">{services.map(([n,title,text,examples,image])=><article key={n}><div className={`design-process-image design-process-${n}${image?" is-single":""}`}><img src={image||"/assets/design-process-studies.png"} alt={`Gestaltungsbeispiel: ${title}`} loading="lazy" width="1536" height="1024"/></div><span className="design-service-number">{n}</span><h3>{title}</h3><p>{text}</p><p className="design-examples">{examples}</p></article>)}</RevealGrid><p className="study-note">Gestaltungsbeispiele zur Veranschaulichung unserer Leistungen.</p></section>
<section className="design-flow"><div className="wrap"><p className="eyebrow">So entsteht Ihre Gestaltung</p><h2>Persönlich besprochen.<br/>Schritt für Schritt entwickelt.</h2><div className="design-flow-grid">{steps.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section id="druckdaten" className="note-band"><h2>Schon eine Vorlage vorhanden?</h2><p>Wir übernehmen bestehende Layouts, passen Formate an und bereiten Ihre Dateien auf. Schicken Sie uns Ihre Vorlagen – den Umfang der Bearbeitung stimmen wir mit Ihnen ab.</p><a href="/druckdaten" className="button black">Vorlagen hochladen</a></section>
<section className="content-section design-web-link"><div><p className="eyebrow line">Ihre Marke im Web</p><h2>Und wie sieht Ihr<br/>digitaler Auftritt aus?</h2><p>Webgestaltung und Programmierung bekommen bei uns ihren eigenen Raum. Entdecken Sie, wie wir Ihre Website neu aufbauen oder weiterentwickeln.</p></div><a className="button black" href="/webdesign">Webgestaltung entdecken <ArrowRight size={18}/></a></section></Page>}
