import {Header,Footer} from "@/components/site-chrome";
import {ArrowRight,ArrowDown,Check} from "lucide-react";
import RevealGrid from "@/components/reveal-grid";
import {webServices,webSteps} from "@/lib/web-services";
export const metadata={title:"Webgestaltung & Programmierung – Webseiten mit Charakter",description:"Individuelle Webseiten, Relaunch und Webprogrammierung. Persönliche Beratung, klare Inhalte und Gestaltung für Smartphone und Desktop."};
const inquiry="/anfrage?produkt=Webseite";
export default function Web(){return <><Header/><main className="web-studio">
<section className="web-hero"><div className="wrap"><div className="web-breadcrumb"><a href="/">OTTO-Druck</a><span>/</span>Webgestaltung & Programmierung</div><div className="web-hero-grid"><div><p className="web-kicker">Design & Entwicklung</p><h1>Webseiten, die<br/><em>Eindruck</em><br/>machen.</h1><p className="web-lead">Ihr Unternehmen verdient einen digitalen Auftritt, der heute zu Ihnen passt. Klar gestaltet. Durchdacht aufgebaut. Persönlich begleitet.</p><a className="web-button" href={inquiry}>Über Ihre Webseite sprechen <ArrowRight size={19}/></a><a className="web-text-link" href="#web-leistungen">Leistungen entdecken <ArrowDown size={16}/></a></div><figure className="web-hero-visual"><img src="/assets/webdesign-studio-de.png" alt="Designstudie mit einer Hotelwebseite auf Monitor und Smartphone" width="1536" height="1024"/><figcaption>Designstudie · Jeder Auftritt wird individuell entwickelt.</figcaption></figure></div><div className="web-principles"><span>Individuelles Webdesign</span><span>Für Smartphone & Desktop</span><span>Ein persönlicher Ansprechpartner</span></div></div></section>
<section className="web-intro wrap"><p className="web-kicker">Mehr als eine digitale Visitenkarte</p><div><h2>Ein guter Auftritt<br/>beginnt mit einer klaren Idee.</h2><p>Was sollen Besucher über Sie erfahren – und was sollen sie als Nächstes tun? Daraus entwickeln wir Struktur, Gestaltung und Funktionen. Für den ersten eigenen Webauftritt genauso wie für die Modernisierung einer bestehenden Webseite.</p></div></section>
<section className="web-examples wrap"><div className="web-section-heading"><p className="web-kicker">So könnte Ihr Auftritt aussehen</p><h2>Drei Ideen.<br/>Drei digitale Möglichkeiten.</h2><p>Von der Unternehmenswebseite bis zur individuellen Funktion: Diese Beispielansichten zeigen mögliche Richtungen für Ihr Projekt.</p></div><RevealGrid className="web-example-grid">{[
["Unternehmenswebseite","Leistungen, Projekte und Kontakt in einem klaren Markenauftritt.","/assets/web-example-company.png"],
["Landingpage","Ein Angebot im Mittelpunkt – mit einem direkten Weg zur nächsten Aktion.","/assets/web-example-landing.png"],
["Individuelle Programmierung","Formulare und Abläufe, die auf Ihren Bedarf abgestimmt werden.","/assets/web-example-code.png"]
].map(([title,text,src],i)=><article key={title}><div className="web-example-image"><img src={src} alt={`Beispielansicht: ${title} mit deutschen Texten`} width="1536" height="1024" loading="lazy"/></div><div className="web-example-caption"><span>0{i+1} / BEISPIELANSICHT</span><h3>{title}</h3><p>{text}</p></div></article>)}</RevealGrid><p className="study-note">Fiktive Gestaltungsbeispiele, keine Kundenreferenzen. Inhalte und Funktionen entwickeln wir passend zu Ihrem Unternehmen.</p></section>
<section className="web-service-section" id="web-leistungen"><div className="wrap"><div className="web-section-heading"><p className="web-kicker">Was wir für Sie entwickeln</p><h2>Ihr Vorhaben.<br/>Die passende Webseite.</h2></div><RevealGrid className="web-service-grid">{webServices.map(s=><article key={s.number}><span className="web-service-number">{s.number}</span><h3>{s.title}</h3><p>{s.text}</p><ul>{s.features.map(f=><li key={f}><Check size={16}/>{f}</li>)}</ul></article>)}</RevealGrid></div></section>
<section className="web-industries wrap"><div><p className="web-kicker">Nah an Ihrem Alltag</p><h2>Für Unternehmen<br/>mit eigenem Charakter.</h2><p>Eine Webseite für ein Hotel braucht andere Inhalte als die eines Handwerksbetriebs. Deshalb beginnen wir bei Ihrem Geschäft und den Fragen Ihrer Besucher.</p></div><div className="web-industry-list"><article><span>01</span><div><h3>Hotels & Gastronomie</h3><p>Atmosphäre vermitteln, Zimmer und Angebote präsentieren, Speisekarten zugänglich machen und Reservierungswege einbinden. Bestehende Buchungssysteme prüfen wir auf passende Anbindung.</p></div></article><article><span>02</span><div><h3>Handwerk & Dienstleistungen</h3><p>Leistungen verständlich erklären, Arbeitsbeispiele zeigen und Anfragen mit den richtigen Angaben erhalten.</p></div></article><article><span>03</span><div><h3>Unternehmen & Marken</h3><p>Kompetenz sichtbar machen, Angebote strukturieren und Ihren Markenauftritt konsequent ins Digitale übertragen.</p></div></article></div></section>
<section className="web-process"><div className="wrap"><p className="web-kicker">Zusammen zum neuen Auftritt</p><h2>Von der ersten Idee<br/>bis zum Livegang.</h2><div className="web-process-grid">{webSteps.map(([title,text],i)=><article key={title}><span>0{i+1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
<section className="web-faq wrap"><div><p className="web-kicker">Gut zu wissen</p><h2>Vor dem Start<br/>klar besprochen.</h2></div><div><article><h3>Kann meine bestehende Domain bleiben?</h3><p>Ja, in der Regel lässt sich Ihre Domain weiterverwenden. Wir prüfen die vorhandene Einrichtung und planen die Umstellung so, dass Webseite und E-Mail berücksichtigt werden.</p></article><article><h3>Was muss ich vorbereiten?</h3><p>Hilfreich sind Ihr Logo, vorhandene Texte und Bilder sowie einige Beispiele, die Ihnen gefallen. Fehlende Inhalte und deren Erstellung besprechen wir gemeinsam.</p></article><article><h3>Was kostet eine Webseite?</h3><p>Das hängt von Seitenumfang, Inhalten und Funktionen ab. Nach dem ersten Gespräch erhalten Sie ein individuelles Angebot. Hosting, Lizenzen und laufende Betreuung weisen wir gesondert aus, soweit sie anfallen.</p></article></div></section>
<section className="web-finale"><div className="wrap"><p className="web-kicker">Neu anfangen. Oder besser weitermachen.</p><h2>Was soll Ihre<br/>Webseite bewegen?</h2><p>Erzählen Sie uns von Ihrem Unternehmen und Ihrer Idee.<br/>Wir besprechen gemeinsam den nächsten Schritt.</p><a href={inquiry} className="web-button">Webseite-Projekt anfragen <ArrowRight size={19}/></a><a href="/gestaltung" className="web-text-link">Auch Logo & Gestaltung benötigt? <ArrowRight size={16}/></a></div></section>
</main><Footer/></>}
