import {ArrowRight} from "lucide-react";
import {Header,Footer,Process,ContactCTA} from "@/components/site-chrome";
import {ProductGrid} from "@/components/product-grid";

export default function Home(){return <><Header/><main>
 <section className="home-hero"><img className="hero-background" src="/assets/hero.webp?v=original-mockup" alt="Illustrative Druckproduktion mit Gestaltungsmonitor und farbigem Druckbogen" fetchPriority="high" width="1536" height="1024"/><div className="hero-wash"/><div className="wrap hero-content"><p className="eyebrow">Ideen auf Papier. Seit 1925.</p><h1>Ihre Ideen<span className="cyan-dot">.</span><br/>In besten<br className="desktop-break"/> Farben<span className="magenta-dot">.</span></h1><p>Druckprodukte, Gestaltung und digitale Medien.<br/>Persönlich begleitet. Präzise umgesetzt.</p><a className="button magenta" href="/produkte">Druckprodukte entdecken <ArrowRight size={19}/></a><div className="hero-caption"><svg className="print-registration" width="38" height="30" viewBox="0 0 38 30" aria-hidden="true" fill="none" stroke="currentColor" strokeWidth=".8"><circle cx="19" cy="15" r="6.5"/><path d="M1 15h36M19 1v28"/></svg> Qualität trifft Kreativität</div></div><div className="hero-registration" aria-hidden="true">C<br/>M<br/>Y<br/>K</div></section>
 <section className="service-band" aria-label="Unsere Leistungen"><a className="service-tile cyan" href="/produkte"><div><p className="eyebrow">Professionell & vielseitig</p><h2>Druckprodukte</h2><p>Von der Visitenkarte bis zum Großformat. Passend zu Ihrem Vorhaben.</p><span>Mehr erfahren <ArrowRight size={18}/></span></div><img src="/assets/flyers.webp" alt="" width="500" height="400"/></a><a className="service-tile magenta" href="/gestaltung"><div><p className="eyebrow">Kreativ & individuell</p><h2>Gestaltung</h2><p>Starke Konzepte und ein stimmiger Auftritt. Von Anfang an mitgedacht.</p><span>Mehr erfahren <ArrowRight size={18}/></span></div><img src="/assets/design.webp" alt="" width="500" height="400"/></a><a className="service-tile yellow" href="/webdesign"><div><p className="eyebrow">Digital & individuell</p><h2>Webgestaltung</h2><p>Websites gestalten und programmieren. Ihr Unternehmen auch online sichtbar.</p><span>Mehr erfahren <ArrowRight size={18}/></span></div><img src="/assets/web-example-code.png" alt="" width="500" height="400"/></a></section>
 <section className="wrap products-section"><div className="section-heading"><div><p className="eyebrow line">Unsere Druckwelt</p><h2>Für jede Idee<br/>das richtige Format.</h2></div><p>Druckprodukte für Unternehmen, Vereine und persönliche Projekte. Entdecken Sie die Möglichkeiten.</p></div><ProductGrid/><p className="small-note">Produktabbildungen zeigen Gestaltungsbeispiele.</p><a className="text-link" href="/produkte">Alle Produkte & Möglichkeiten <ArrowRight size={18}/></a></section>
 <section className="heritage-section"><div className="wrap heritage-inner"><div><p className="eyebrow">Dresdner Drucktradition. Weitergedacht.</p><h2>Erfahrung im Rücken.<br/>Ihre Idee im Blick.</h2></div><div><p>Unsere Wurzeln reichen bis 1925 zurück. Heute verbinden wir dieses Wissen mit Gestaltung, persönlicher Beratung und einem vielseitigen Produktionsnetzwerk.</p><a className="text-link" href="/ueber-uns">OTTO-Druck kennenlernen <ArrowRight size={18}/></a></div></div></section>
 <Process/><ContactCTA/>
 </main><Footer/></>}