"use client";
import {useState,useEffect,useRef,FormEvent} from 'react';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {printProfile,coverMaterials,finishesFor,updatePrintData,validatePrintOptions,CUSTOM} from '@/lib/print-options';
import {Progress} from '@/components/ui/progress';
import {ArrowRight,ArrowLeft,Check} from 'lucide-react';
export const categories:Record<string,string[]>={"Geschäftsausstattung":["Visitenkarten","Briefbogen","Briefumschläge","Blöcke","Mappen","Sonstiges"],"Flyer & Werbung":["Flyer","Falzflyer","Postkarten","Einladungen","Sonstiges"],"Broschüren":["Imagebroschüre","Produktkatalog","Magazin","Sonstiges"],"Bücher":["Hardcover","Softcover","Chronik","Sonstiges"],"Plakate":["Poster","Großformatplakat","Kunstdruck","Sonstiges"],"Werbetechnik":["Roll-up","Banner","Schild","Folienbeschriftung","Sonstiges"],"Verpackungen":["Faltschachtel","Versandverpackung","Geschenkverpackung","Sonstiges"],"Taschen & Beutel":["Papiertragetasche","Baumwolltasche","Werbebeutel","Sonstiges"],"Mailing":["Anschreiben mit Umschlag","Selfmailer","Postkartenmailing","Sonstiges"],"Aufkleber & Etiketten":["Rollenetiketten","Bogenetiketten","Kontursticker","Sonstiges"],"Sonstiges":["Individuelles Druckprodukt","Beratung gewünscht"],"Grafik & Gestaltung":["Logo & Corporate Design","Layout & Satz","Druckdaten erstellen","Bestehende Gestaltung überarbeiten"],"Webseite":["Neue Website","Bestehende Website überarbeiten","Programmierung","Beratung gewünscht"]};
export const dataOptions=['Druckfertige PDF vorhanden','Daten vorhanden – bitte Druckdaten prüfen','Gestaltung teilweise vorhanden – Layout überarbeiten','Gestaltung vollständig durch OTTO-Druck'];
const steps=['Bedarf','Produkt','Eckdaten','Druckdaten','Kontakt & Prüfung'];
const labels:Record<string,string>={category:'Bedarf',product:'Produkt',quantity:'Auflage',format:'Format',pages:'Seitenzahl',color:'Farbigkeit Vorderseite',printSides:'Bedruckung',backColor:'Farbigkeit Rückseite',paper:'Material/Papier',material:'Material / Papier',grammage:'Grammatur / Materialstärke',adhesion:'Haftung',customFormat:'Wunschmaß in mm',orientation:'Ausrichtung',coverMaterial:'Umschlagmaterial',coverGrammage:'Grammatur Umschlag',finishing:'Veredelung',delivery:'Lieferort',dataStatus:'Stand der Druckdaten',name:'Name',company:'Firma',email:'E-Mail',phone:'Telefon',message:'Weitere Wünsche'};
export default function InquiryForm(){const [step,setStep]=useState(0),[data,setData]=useState<Record<string,string>>({dataStatus:dataOptions[3]}),[privacy,setPrivacy]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[result,setResult]=useState('');
const stepHeading=useRef<HTMLHeadingElement>(null);
const successHeading=useRef<HTMLHeadingElement>(null);
const [emailSent,setEmailSent]=useState(false);
const [copied,setCopied]=useState(false);
useEffect(()=>{
  if(step===0&&!result)return;
  let frame=0;
  const move=()=>{
    const heading=result?successHeading.current:stepHeading.current;
    if(!heading)return;
    heading.focus({preventScroll:true});
    const header=document.querySelector('.site-header')?.getBoundingClientRect().height||100;
    window.scrollTo({top:Math.max(0,window.scrollY+heading.getBoundingClientRect().top-header-24),behavior:'instant'});
  };
  frame=requestAnimationFrame(move);
  const timer=window.setTimeout(move,180);
  return ()=>{cancelAnimationFrame(frame);clearTimeout(timer)};
},[step,result]);
const update=(key:string,value:string)=>setData(d=>updatePrintData(d,key,value));
const sided=data.category==='Geschäftsausstattung'&&['Visitenkarten','Briefbogen'].includes(data.product);
const profile=printProfile(data.category,data.product,data.format);
const material=profile.materials.find(m=>m.name===data.material);
const cover=coverMaterials.find(m=>m.name===data.coverMaterial);
const finishes=finishesFor(data);
const customSize=data.format===CUSTOM||data.category==='Aufkleber & Etiketten'&&data.product==='Rollenetiketten'&&!!data.format;
useEffect(()=>{const product=new URLSearchParams(location.search).get('produkt');if(product){const aliases:Record<string,string>={'Broschüren & Kataloge':'Broschüren','Bücher & Hardcover':'Bücher','Mailings':'Mailing','Plakate & Großformat':'Plakate','Etiketten & Aufkleber':'Aufkleber & Etiketten'};const category=aliases[product]||product;if(categories[category])setData(d=>({...d,category}));}},[]);
async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');if(step===2||step===4){const problem=validatePrintOptions(data);if(problem){setError(problem);return}}if(step<4){setStep(step+1);return}setBusy(true);try{const response=await fetch('/api/anfragen',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...data,privacy})});const body=await response.json() as {id:string,error?:string,emailSent?:boolean};if(!response.ok)throw new Error(body.error||'Die Anfrage konnte nicht gesendet werden.');setEmailSent(body.emailSent===true);setResult(body.id);}catch(e){setError(e instanceof Error?e.message:'Bitte erneut versuchen.')}finally{setBusy(false)}}
function field(key:string,type='text',placeholder=''){return <label>{labels[key]}<Input name={key} type={type} value={data[key]||''} onChange={e=>update(key,e.target.value)} maxLength={key==='email'?250:300} min={type==='number'?1:undefined} placeholder={placeholder} required={['name','email'].includes(key)}/></label>}
function select(key:string,options:string[],label=labels[key],disabled=false){return <label>{label}<NativeSelect name={key} required={sided&&['printSides','color','backColor'].includes(key)} disabled={disabled} value={data[key]||''} onChange={e=>update(key,e.target.value)}><NativeSelectOption value="">Bitte auswählen</NativeSelectOption>{options.map(o=><NativeSelectOption key={o} value={o}>{o}</NativeSelectOption>)}</NativeSelect></label>}
if(result)return <section className="intake-success" role="status"><Check size={38}/><h2 ref={successHeading} tabIndex={-1}>Ihre Anfrage ist eingegangen.</h2><p>Wir haben Ihre Angaben gespeichert und melden uns persönlich bei Ihnen.</p><p>Ihre Referenz: <strong>{result}</strong></p><button type="button" className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(result);setCopied(true)}catch{setCopied(false)}}}>{copied?'Referenz kopiert':'Referenz kopieren'}</button><p>{emailSent?'Eine Bestätigung mit Referenz und Upload-Link wurde zum E-Mail-Versand übergeben. Bitte prüfen Sie auch Ihren Spamordner.':'Bitte bewahren Sie Ihre Referenz auf. Eine automatische E-Mail-Bestätigung konnte derzeit nicht versendet werden. Ihre Anfrage ist trotzdem gespeichert; bitte nicht erneut absenden.'}</p><h3>Druckdaten noch nicht bereit?</h3><p>Sie können Ihre Dateien auch später über „Druckdaten hochladen“ auf unserer Website nachreichen. Geben Sie dort Ihre Referenz und dieselbe E-Mail-Adresse an, damit wir die Dateien Ihrer Anfrage zuordnen können. Wenn Sie noch keine Daten haben, besprechen wir die Gestaltung mit Ihnen.</p><a className="button black" href={`/druckdaten?referenz=${encodeURIComponent(result)}`}>Druckdaten jetzt hochladen <ArrowRight size={18}/></a><p><a href="/">Zur Startseite</a></p><p className="small-note">Dies ist eine unverbindliche Anfrage, keine Bestellung.</p></section>;
return <form onSubmit={submit} className="intake-form"><ol className="form-steps">{steps.map((title,i)=><li key={title} className={step===i?'current':step>i?'done':''} aria-current={step===i?'step':undefined}><span>{i+1}</span>{title}</li>)}</ol><Progress value={(step+1)*20} aria-label={`Schritt ${step+1} von 5`}/><div className="intake-step" key={step}><p className="eyebrow">Schritt {step+1} von 5</p><h2 ref={stepHeading} tabIndex={-1}>{['Was benötigen Sie?','Welches Produkt planen Sie?','Die Eckdaten Ihres Projekts.','Wie weit ist Ihre Gestaltung?','So erreichen wir Sie.'][step]}</h2>{step===0&&<div className="choice-grid">{Object.keys(categories).map(c=><label className={`choice ${data.category===c?'selected':''}`} key={c}><input type="radio" name="category" value={c} checked={data.category===c} onChange={()=>update('category',c)} required/><span>{c}</span></label>)}</div>}{step===1&&<><p>{data.category}</p><div className="choice-grid">{(categories[data.category]||[]).map(p=><label className={`choice ${data.product===p?'selected':''}`} key={p}><input required type="radio" name="product" checked={data.product===p} onChange={()=>update('product',p)}/><span>{p}</span></label>)}</div></>}{step===2&&<><p>Was Sie noch nicht wissen, lassen Sie einfach offen. Wir beraten Sie.</p>{!['Webseite','Grafik & Gestaltung'].includes(data.category)&&<div className="form-row">{field('quantity','number','z. B. 500')}
{select('format',profile.formats,profile.formatLabel||'Endformat')}
{customSize&&field('customFormat','text',data.product==='Papiertragetasche'||data.category==='Verpackungen'?'Breite × Höhe × Tiefe in mm':'Breite × Höhe oder Durchmesser in mm')}
{data.category!=='Aufkleber & Etiketten'&&data.category!=='Verpackungen'&&data.category!=='Taschen & Beutel'&&select('orientation',['Hochformat','Querformat'])}
{profile.pages&&field('pages','number',data.category==='Broschüren'||data.category==='Bücher'?'Inhaltsseiten ohne Umschlag':'Gesamtseitenzahl')}
{sided&&select('printSides',['Einseitig','Beidseitig'])}
{select('color',profile.colors,sided?'Farbigkeit Vorderseite':'Farbigkeit')}
{sided&&data.printSides==='Beidseitig'&&select('backColor',profile.colors)}
{profile.freeMaterial&&field('material','text','Material oder Ausführung, falls bekannt')}
{profile.materials.length>0&&select('material',profile.materials.map(m=>m.name),data.category==='Broschüren'||data.category==='Bücher'?'Material / Papier – Inhalt':'Material / Papier')}
{profile.materials.some(m=>m.weights.length>0)&&select('grammage',material?.weights||[],'Grammatur / Materialstärke',!material||!material.weights.length)}
{material?.adhesion&&select('adhesion',material.adhesion)}
{finishes.length>0&&select('finishing',finishes)}
{data.category==='Broschüren'&&<>{select('coverMaterial',coverMaterials.map(m=>m.name))}{select('coverGrammage',cover?.weights||[],labels.coverGrammage,!cover)}</>}
{field('delivery','text','PLZ / Ort')}</div>}
{profile.note&&!['Webseite','Grafik & Gestaltung'].includes(data.category)&&<p className="form-hint">{profile.note}</p>}
<label>{data.category==='Webseite'?'Funktionen, Seitenumfang und vorhandene Website':data.category==='Grafik & Gestaltung'?'Ziel, Stilrichtung und vorhandene Vorlagen':'Weitere Wünsche'}<Textarea className="project-wishes" rows={10} value={data.message||''} onChange={e=>update('message',e.target.value)} maxLength={4000}/></label></>}{step===3&&<><div className="choice-grid single">{dataOptions.map(o=><label className={`choice ${data.dataStatus===o?'selected':''}`} key={o}><input type="radio" name="dataStatus" checked={data.dataStatus===o} onChange={()=>update('dataStatus',o)} required/><span>{o}</span></label>)}</div><p className="form-hint">Dateien können Sie nach dem Absenden über den separaten Druckdaten-Upload zuordnen. Für eine Website-Anfrage wählen Sie hier den Stand Ihrer Gestaltung und Vorlagen.</p>{data.category==='Mailing'&&<p className="form-hint">Bitte keine Adresslisten in die Anfrage aufnehmen. Die geschützte Übertragung personenbezogener Mailingdaten vereinbaren wir separat.</p>}</>}{step===4&&<><div className="form-row">{field('name')}{field('company')}{field('email','email')}{field('phone','tel')}</div><details className="request-summary" open><summary>Ihre Projektangaben prüfen</summary><dl>{Object.entries(data).filter(([k,v])=>v&&!['name','company','email','phone'].includes(k)).map(([k,v])=><div key={k}><dt>{labels[k]||k}</dt><dd>{v}</dd></div>)}</dl></details><label className="check-label"><input type="checkbox" checked={privacy} onChange={e=>setPrivacy(e.target.checked)} required/><span>Ich habe die <a href="/datenschutz" target="_blank" rel="noopener">Datenschutzhinweise</a> gelesen. Meine Angaben werden zur Bearbeitung dieser Anfrage verwendet.</span></label><p className="form-hint">Unverbindlich und ohne automatische Preisberechnung. Mit dem Absenden erteilen Sie noch keinen Druckauftrag.</p><p className="form-hint">Nach Angebotsannahme erhalten Sie Ihre Vorausrechnung. Zahlung per Überweisung oder, sofern von Ihrer Bank unterstützt, per Echtzeitüberweisung. Nach vollständigem Zahlungseingang, druckfähigen Daten und Druckfreigabe veranlassen wir die Produktion. Die Zahlungsdaten erhalten Sie mit der Rechnung. <a href="/agb#zahlung">Zahlungsbedingungen ansehen</a>.</p></>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="form-navigation">{step>0&&<button className="button outline" type="button" disabled={busy} onClick={()=>{setStep(step-1);setError('')}}><ArrowLeft size={18}/>Zurück</button>}<button className="button magenta" disabled={busy} type="submit">{busy?'Wird übermittelt …':step===4?'Anfrage absenden':'Weiter'}<ArrowRight size={18}/></button></div></form>}
