"use client";

import { useState, useEffect } from "react";
import { ArrowRight, MapPin, Mail, Phone, Menu, MessageSquareText, Layers, PackageCheck, X } from "lucide-react";
import {products} from "@/lib/products";
import { Sheet, SheetContent, SheetTitle, SheetTrigger, SheetClose } from "@/components/ui/sheet";

const nav = [["Druckprodukte", "/produkte"], ["Design & Medien", "/gestaltung"], ["Webgestaltung", "/webdesign"], ["Über uns", "/ueber-uns"], ["Referenzen", "/referenzen"], ["Kontakt", "/kontakt"]];
function BrandMark({inverse=false}:{inverse?:boolean}){const maskId=inverse?"otto-footer-mask":"otto-header-mask";return <svg className="logo" viewBox="0 0 1500 1049" role="img" aria-label="OTTO-Druck" xmlns="http://www.w3.org/2000/svg"><defs><filter id="otto-footer-white" x="0" y="0" width="100%" height="100%" colorInterpolationFilters="sRGB"><feColorMatrix type="matrix" values="0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 1 0"/></filter><mask id={maskId}><rect width="1500" height="1049" fill="white"/><rect x="450" y="850" width="600" height="100" fill="black"/><path d="M60 60h160v160H60z M1280 60h160v160h-160z M60 840h160v150H60z M1280 840h160v150h-160z" fill="black"/></mask></defs><image href="/assets/logo.png?v=original-wordmark" width="1500" height="1049" mask={`url(#${maskId})`} filter={inverse?"url(#otto-footer-white)":undefined}/>{/* Preserve the approved glyphs; only increase the spacing between DRUCK letters. */}{[[495,565,-60],[610,675,-30],[718,785,0],[824,898,30],[941,1010,60]].map(([left,right,offset])=><svg key={left} x={left+offset} y={850} width={right-left} height={100} viewBox={`${left} 850 ${right-left} 100`} overflow="hidden"><image href="/assets/logo.png?v=original-wordmark" width="1500" height="1049" filter={inverse?"url(#otto-footer-white)":undefined}/></svg>)}<g fill="none" strokeWidth="20" strokeLinecap="square" strokeLinejoin="miter"><path d="M176 104H103V178" stroke="#00ACE0"/><path d="M1324 104H1397V178" stroke="#EC008C"/><path d="M103 872V945H176" stroke="#FFE500"/><path d="M1397 872V945H1324" stroke={inverse?"#FFFFFF":"#000000"}/></g></svg>}
export function Logo(){return <BrandMark/>;}

export function Header(){const [open,setOpen]=useState(false);const [compact,setCompact]=useState(false);useEffect(()=>{const update=()=>setCompact(window.scrollY>40);update();window.addEventListener("scroll",update,{passive:true});return ()=>window.removeEventListener("scroll",update)},[]);return <>
  <div className="topbar"><div className="wrap topbar-inner"><span><MapPin size={14}/> Druck & Medien aus Dresden</span><a href="mailto:post@otto-druck.de"><Mail size={14}/> post@otto-druck.de</a><a href="tel:+493515014904" className="top-phone"><Phone size={14}/> 0351 501 49 04</a><a className="top-upload" href="/druckdaten">Druckdaten hochladen</a><span className="ink-dots" aria-label="Cyan, Magenta, Gelb und Schwarz"><i/><i/><i/><i/></span></div></div>
  <header className={`site-header ${compact?"compact":""}`}><div className="wrap header-inner"><a href="/" className="brand"><Logo/></a><nav className="desktop-nav" aria-label="Hauptnavigation">{nav.map(([name,url])=><div className="nav-item" key={url}><a href={url}>{name}</a>{url==="/produkte"&&<div className="nav-dropdown">{products.map(p=><a key={p.slug} href={`/produkte/${p.slug}`}>{p.title}</a>)}</div>}</div>)}</nav><div className="header-split" aria-label="Projekt und Kundenportal"><a href="/anfrage"><span className="split-long">Projekt anfragen</span><span className="split-short">Anfrage</span></a><a href="https://portal.otto-druck.de/"><span className="split-long">Kundenportal</span><span className="split-short">Portal</span></a></div><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-toggle" aria-label="Menü öffnen"><Menu/></button></SheetTrigger><SheetContent className="mobile-sheet" showCloseButton={false}><div className="mobile-sheet-heading"><SheetTitle>OTTO-Druck</SheetTitle><SheetClose asChild><button aria-label="Menü schließen"><X/></button></SheetClose></div><nav aria-label="Mobile Navigation"><a href="/">Startseite</a>{nav.map(([name,url])=><a href={url} key={url} onClick={()=>setOpen(false)}>{name}<ArrowRight size={18}/></a>)}<a href="/anfrage">Projekt anfragen</a><a href="/druckdaten">Druckdaten hochladen</a><a href="https://portal.otto-druck.de/">Kundenportal</a></nav><a href="tel:+493515014904">0351 501 49 04</a><a href="mailto:post@otto-druck.de">post@otto-druck.de</a></SheetContent></Sheet></div></header>
</>}

export function Footer(){const [socialNotice,setSocialNotice]=useState("");return <footer className="site-footer"><div className="wrap footer-main"><div className="footer-brand"><a className="footer-logo" href="/"><BrandMark inverse/></a><p>Druck & Medien aus Dresden.<br/>Persönlich. Kreativ. Vielseitig.</p><div className="socials" aria-label="Social Media – Profile folgen"><button type="button" onClick={()=>setSocialNotice("Unser Facebook-Profil wird noch eingerichtet.")} title="Facebook – Profil folgt" aria-label="Facebook – Profil folgt"><b aria-hidden="true">f</b></button><button type="button" onClick={()=>setSocialNotice("Unser Instagram-Profil wird noch eingerichtet.")} title="Instagram – Profil folgt" aria-label="Instagram – Profil folgt"><svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><circle cx="17.5" cy="6.5" r="1" fill="currentColor" stroke="none"/></svg></button><button type="button" onClick={()=>setSocialNotice("Unser LinkedIn-Profil wird noch eingerichtet.")} title="LinkedIn – Profil folgt" aria-label="LinkedIn – Profil folgt"><b aria-hidden="true">in</b></button><small role="status">{socialNotice||"Unsere Profile folgen."}</small></div></div><div><h3>Entdecken</h3>{nav.slice(0,5).map(([name,url])=><a key={url} href={url}>{name}</a>)}<a href="/anfrage">Projektanfrage</a><a href="/druckdaten">Druckdaten hochladen</a><a href="https://portal.otto-druck.de/">Kundenportal</a></div><div><h3>Direkter Kontakt</h3><a href="mailto:post@otto-druck.de">post@otto-druck.de</a><a href="tel:+493515014904">0351 501 49 04</a><a href="tel:+4917680250200">0176 80 250 200</a><p>Meschwitzstraße 1<br/>01099 Dresden</p></div></div><div className="wrap footer-bottom"><span>OTTO-Druck · Ein Unternehmen der NOXIQ GmbH</span><nav aria-label="Rechtliche Informationen"><a href="/impressum">Impressum</a><a href="/datenschutz">Datenschutz</a><a href="/agb">AGB</a><button onClick={()=>window.dispatchEvent(new Event("otto:privacy"))}>Cookie-Einstellungen</button></nav></div></footer>}

export function Page({eyebrow,title,intro,children,image,dark=false}:{eyebrow:string,title:string,intro:string,children:React.ReactNode,image?:string,dark?:boolean}){return <><Header/><main><section className={`page-hero ${image?"has-image":""} ${dark?"dark":""}`}>{image&&<img src={image} alt="" className="page-hero-image"/>}<div className="wrap"><div className="breadcrumbs"><a href="/">Startseite</a><span>/</span><span>{eyebrow}</span></div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="page-intro">{intro}</p></div></section>{children}</main><Footer/></>}

export function Process(){const steps=[{Icon:MessageSquareText,title:"Idee besprechen",text:"Wir hören zu, beraten persönlich und finden das passende Format."},{Icon:Layers,title:"Gestaltung & Druck",text:"Von der ersten Gestaltung bis zur abgestimmten Produktion."},{Icon:PackageCheck,title:"Fertig geliefert",text:"Sorgfältig verarbeitet und an Ihren Wunschort geliefert."}];return <section className="process-section wrap"><p className="eyebrow">So einfach geht’s</p><div className="process-row">{steps.map(({Icon,title,text},i)=><article key={title} className="process-step"><Icon size={40} strokeWidth={1.2}/><span className={`step-number color-${i}`}>0{i+1}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>}

export function ContactCTA(){return <section className="contact-cta"><div className="wrap"><div><p className="eyebrow">Gemeinsam mehr möglich machen</p><h2>Bereit für Ihren nächsten Druckauftrag?</h2></div><a className="button yellow" href="/anfrage">Jetzt Projekt anfragen <ArrowRight size={19}/></a></div></section>}
