const original = [
 {slug:"geschaeftsausstattung",title:"Geschäftsausstattung",image:"stationery",intro:"Ein stimmiger Auftritt beginnt beim ersten Eindruck. Wir bringen Ihre Marke auf Papier – vom persönlichen Kontakt bis zur täglichen Korrespondenz.",items:["Visitenkarten","Briefbogen & Rechnungsbogen","Briefumschläge","Blöcke & Formulare","Präsentationsmappen","Stempel"],options:["Naturpapier, Bilderdruck oder strukturierte Papiere","Matt, glänzend oder mit besonderer Haptik","Prägung, Folie und partielle Veredelung auf Anfrage"]},
 {slug:"flyer-broschueren",title:"Flyer & Broschüren",image:"brochures-final",intro:"Kompakte Botschaft oder ausführliche Vorstellung: Wir geben Ihren Inhalten Raum, Rhythmus und das passende Format.",items:["Flyer & Falzflyer","Folder & Broschüren","Magazine","Postkarten","Einladungen","Speise- & Getränkekarten"],options:["Individuelle Formate und Falzarten","Rückstichheftung, Klebebindung oder Spiralbindung","Datenprüfung und Gestaltung nach Absprache"]},
 {slug:"verpackungen-taschen",title:"Verpackungen & Taschen",image:"packaging",intro:"Verpackungen schützen Ihr Produkt und tragen Ihre Marke weiter. Gemeinsam finden wir eine Lösung, die Inhalt, Anlass und Budget verbindet.",items:["Faltschachteln","Produktverpackungen","Versandverpackungen","Papiertragetaschen","Beutel & Tüten","Geschenkverpackungen"],options:["Material und Ausführung passend zum Einsatzzweck","Individuelle Bedruckung und Formate auf Anfrage","Stanzung, Veredelung und Konfektionierung"]},
 {slug:"werbetechnik",title:"Werbetechnik",image:"signage",intro:"Große Ideen brauchen große Flächen. Für Messe, Geschäft, Veranstaltung oder Außenauftritt setzen wir Ihre Botschaft sichtbar in Szene.",items:["Banner & Planen","Plakate & Poster","Schilder","Roll-ups & Displays","Folien & Beschriftung","Messeausstattung"],options:["Für Innen- und Außenbereiche","Materialauswahl nach Standort und Nutzungsdauer","Konfektionierung und Befestigung nach Projekt"]},
 {slug:"etiketten-aufkleber",title:"Etiketten & Aufkleber",image:"labels",intro:"Kleine Fläche, klare Botschaft. Ob Produktkennzeichnung, Versand oder Werbung: Das passende Etikett macht den Unterschied.",items:["Rollenetiketten","Bogenetiketten","Produktaufkleber","Adressetiketten","Konturgeschnittene Sticker","Siegelaufkleber"],options:["Papier oder Folie, je nach Untergrund und Anwendung","Individuelle Konturen und Formate","Haftung, Oberfläche und Beständigkeit passend auswählen"]},
 {slug:"buecher-kataloge",title:"Bücher & Kataloge",image:"books",intro:"Inhalte, die bleiben. Von der Chronik bis zum Produktkatalog begleiten wir Ihr Projekt mit Erfahrung in Gestaltung, Material und Bindung.",items:["Hardcover & Softcover","Produktkataloge","Chroniken","Publikationen","Abschlussarbeiten","Kalender"],options:["Papier und Bindung passend zu Umfang und Nutzung","Kleine und größere Auflagen nach Angebot","Umschlaggestaltung, Satz und Druckdatenaufbereitung"]}
];

export const products = [
 original[0],
 {...original[1],slug:"flyer-werbung",title:"Flyer & Werbung",image:"flyers",items:["Flyer & Falzflyer","Postkarten","Einladungen","Folder","Speise- & Getränkekarten"]},
 {...original[1],slug:"broschueren-kataloge",title:"Broschüren & Kataloge",items:["Imagebroschüren","Produktkataloge","Magazine","Vereinshefte","Geschäftsberichte"]},
 {...original[5],slug:"buecher-hardcover",title:"Bücher & Hardcover",items:["Hardcover & Softcover","Chroniken","Publikationen","Abschlussarbeiten","Kalender"]},
 original[4],
 {...original[3],slug:"plakate-grossformat",title:"Plakate & Großformat",image:"posters",items:["Plakate & Poster","Großformatdrucke","Kunstdrucke","Aktionsplakate"]},
 original[3],
 {...original[2],slug:"verpackungen",title:"Verpackungen",items:["Faltschachteln","Produktverpackungen","Versandverpackungen","Geschenkverpackungen"]},
 {...original[2],slug:"taschen-beutel",title:"Taschen & Beutel",image:"bags",items:["Papiertragetaschen","Baumwolltaschen","Werbebeutel","Geschenktüten"]},
 {slug:"mailings",title:"Mailings",image:"mailings",intro:"Persönliche Post, die ankommt. Wir begleiten Ihre Mailingaktion von der Gestaltung und Personalisierung bis zur Versandvorbereitung.",items:["Personalisierte Anschreiben","Selfmailer & Postkarten","Adressierte Umschläge","Beilagen, Falzen & Kuvertieren","Frankierung & Postauflieferung nach Absprache"],options:["Auflage, Varianten und Versandtermin gemeinsam planen","Personalisierung und Datenstruktur vorab abstimmen","Adressdaten ausschließlich nach Vereinbarung sicher übermitteln"]}
];
export const legacyProductSlugs: Record<string,string>={"flyer-broschueren":"broschueren-kataloge","verpackungen-taschen":"verpackungen","buecher-kataloge":"buecher-hardcover"};
