import {newReference} from '@/lib/reference';
import {sendIntakeMail} from '@/lib/mail';
import {validatePrintOptions} from '@/lib/print-options';
import {storage,textField,validContact,checkRequest,rateKey,limited,cleanup,noStore,boundedBody} from '@/lib/intake';
export async function POST(req:Request){try{if(!await checkRequest(req))return Response.json({error:'Ungültiger Ursprung.'},{status:403});if(Number(req.headers.get('content-length'))>20000)return Response.json({error:'Die Anfrage ist zu groß.'},{status:413});const raw=await (await boundedBody(req,20000)).json();if(!raw||typeof raw!=="object"||Array.isArray(raw))return Response.json({error:"Ungültige Angaben."},{status:400});const data=raw as Record<string,unknown>;const name=textField(data.name),email=textField(data.email,250);if(!validContact(name,email)||!textField(data.category)||!textField(data.product)||data.privacy!==true)return Response.json({error:'Bitte ergänzen Sie Name, gültige E-Mail, Bedarf und Produkt.'},{status:400});const key=await rateKey(req);if(await limited(key))return Response.json({error:'Zu viele Anfragen. Bitte versuchen Sie es später erneut oder rufen Sie uns an.'},{status:429});const allowed=['category','product','quantity','format','pages','color','printSides','backColor','paper','material','grammage','adhesion','customFormat','orientation','coverMaterial','coverGrammage','finishing','delivery','dataStatus','company','phone','message'];const details=Object.fromEntries(allowed.map(k=>[k,textField(data[k],k==='message'?4000:500)]));const optionError=validatePrintOptions(details);if(optionError)return Response.json({error:optionError},{status:400});let id=newReference();const now=Date.now();await cleanup();for(let attempt=0;;attempt++){
try{await storage().db.prepare('INSERT INTO submissions (id,kind,name,email,details,created,expires,rate_key) VALUES (?,?,?,?,?,?,?,?)').bind(id,'Anfrage',name,email,JSON.stringify({...details,_notification:'pending'}),now,now+90*86400000,key).run();break;}
catch(error){if(attempt>=4||!String(error).includes('UNIQUE constraint failed: submissions.id'))throw error;id=newReference();}}
let mail={owner:false,customer:false};
try{mail=await sendIntakeMail(id,name,email,details);}catch{console.error('Notification failed',id);}
try{await storage().db.prepare('UPDATE submissions SET details=? WHERE id=?').bind(JSON.stringify({...details,_notification:JSON.stringify(mail)}),id).run();}catch{console.error('Notification status not saved',id);}
return Response.json({id,emailSent:mail.customer},{headers:noStore});}catch(e){if(e instanceof RangeError)return Response.json({error:'Die Anfrage ist zu groß.'},{status:413});console.error('Inquiry storage failed',e);return Response.json({error:'Ihre Anfrage konnte nicht gespeichert werden. Ihre Eingaben bleiben erhalten. Bitte versuchen Sie es erneut.'},{status:503,headers:noStore});}}
